export const TOOL_SCHEMAS = {
  milling: {
    label: "Фреза",
    fields: [
      {
        type: "number",
        name: "amount",
        label: "Количество, шт",
        required: true,
        min: 0,
        unit: "шт",
      },
      {
        type: "select",
        name: "coating",
        label: "Покрытие",
        required: true,
        options: [
          { value: "Алмазное", label: "Алмазное" },
          { value: "Без покрытия", label: "Без покрытия" },
          { value: "С покрытием", label: "С покрытием" },
        ],
      },
      {
        type: "select",
        name: "processing-material",
        label: "Материал обработки",
        required: true,
        options: [
          { value: "H (твердые материалы)", label: "H (твердые материалы)" },
          { value: "K (чугун)", label: "K (чугун)" },
          { value: "M (нержавеющая сталь)", label: "M (нержавеющая сталь)" },
          { value: "N (цветные металлы)", label: "N (цветные металлы)" },
          { value: "P (сталь)", label: "P (сталь)" },
          { value: "S (жаропрочные)", label: "S (жаропрочные)" },
        ],
      },
      {
        type: "select",
        name: "milling-type",
        label: "Тип фрезы",
        required: true,
        options: [
          { value: "Галтельная", label: "Галтельная" },
          {
            value: "Дисковая трехсторонняя /пазовая",
            label: "Дисковая трехсторонняя /пазовая",
          },
          { value: "Концевая", label: "Концевая" },
          { value: "Насадная", label: "Насадная" },
          { value: "Дисковая отрезная", label: "Дисковая отрезная" },
          { value: "Радиусная", label: "Радиусная" },
          { value: "Резьбовая", label: "Резьбовая" },
          { value: "Сферическая", label: "Сферическая" },
          { value: "Фасочная", label: "Фасочная" },
          { value: "Шпоночная", label: "Шпоночная" },
        ],
      },
      {
        type: "select",
        name: "cooling-type",
        label: "Тип охлаждения",
        required: true,
        options: [
          { value: "Внутреннее", label: "Внутреннее" },
          { value: "Наружнее", label: "Наружнее" },
          { value: "Нет", label: "Нет" },
        ],
      },
      {
        type: "select",
        name: "hrc",
        label: "HRC",
        required: true,
        options: [
          { value: "< 35 HRC", label: "< 35 HRC" },
          { value: "< 40 HRC", label: "< 40 HRC" },
          { value: "< 50 HRC", label: "< 50 HRC" },
          { value: "< 55 HRC", label: "< 55 HRC" },
          { value: "< 60 HRC", label: "< 60 HRC" },
          { value: "< 68 HRC", label: "< 68 HRC" },
        ],
      },
      {
        type: "number",
        name: "total-length",
        label: "Общая длина",
        required: true,
        min: 0,
        unit: "мм",
      },
      {
        type: "number",
        name: "length-working-part",
        label: "Длина рабочей части",
        required: true,
        min: 0,
        unit: "мм",
      },
      {
        type: "number",
        name: "diameter-working-part",
        label: "Диаметр рабочей части",
        required: true,
        min: 0,
        unit: "мм",
      },
      {
        type: "number",
        name: "shank-diameter",
        label: "Диаметр хвостовика",
        required: true,
        min: 0,
        unit: "мм",
      },
      {
        type: "number",
        name: "number-cutting-edges",
        label: "Число режущих кромок",
        min: 0,
        unit: "мм",
      },
      {
        type: "textarea",
        name: "comment",
        label: "Здесь вы можете оставить комментарий к заказу",
      },
    ],
  },

  drillings: {
    label: "Сверлa",
    fields: [
      {
        type: "number",
        name: "amount",
        label: "Количество",
        required: true,
        min: 0,
        unit: "шт",
      },
      {
        type: "select",
        name: "view",
        label: "Вид",
        required: false,
        options: [
          { value: "Длинное", label: "Длинное" },
          { value: "Сверхдлинное", label: "Сверхдлинное" },
          { value: "Среднее", label: "Среднее" },
          { value: "Удлиненное", label: "Удлиненное" },
        ],
      },
      {
        type: "number",
        name: "drilling-depth",
        label: "Глубина сверления",
        required: true,
        min: 0,
        unit: "мм",
      },
      {
        type: "select",
        name: "processing-material",
        label: "Материал обработки",
        required: false,
        options: [
          { value: "H (твердые материалы)", label: "H (твердые материалы)" },
          { value: "K (чугун)", label: "K (чугун)" },
          { value: "M (нержавеющая сталь)", label: "M (нержавеющая сталь)" },
          { value: "N (цветные металлы)", label: "N (цветные металлы)" },
          { value: "P (сталь)", label: "P (сталь)" },
          { value: "S (жаропрочные)", label: "S (жаропрочные)" },
        ],
      },
      {
        type: "text",
        name: "tool-material",
        label: "Материал инстурмента",
      },
      {
        type: "select",
        name: "cooling-type",
        label: "Тип охлаждения",
        required: true,
        options: [
          { value: "Внутреннее", label: "Внутреннее" },
          { value: "Наружнее", label: "Наружнее" },
          { value: "Нет", label: "Нет" },
        ],
      },
      {
        type: "select",
        name: "hrc",
        label: "HRC",
        required: true,
        options: [
          { value: "< 50 HRC", label: "< 50 HRC" },
          { value: "< 55 HRC", label: "< 55 HRC" },
          { value: "< 60 HRC", label: "< 60 HRC" },
          { value: "< 68 HRC", label: "< 68 HRC" },
        ],
      },
      {
        type: "number",
        name: "case-diameter",
        label: "Диаметр корпуса",
        min: 0,
        unit: "мм",
      },
      {
        type: "number",
        name: "diameter",
        label: "Диаметр",
        min: 0,
        unit: "мм",
      },
      {
        type: "number",
        name: "total-length",
        label: "Общая длина",
        required: true,
        min: 0,
        unit: "мм",
      },
      {
        type: "number",
        name: "length-working-part",
        label: "Длина рабочей части",
        required: true,
        min: 0,
        unit: "мм",
      },
      {
        type: "number",
        name: "diameter-working-part",
        label: "Диаметр рабочей части",
        required: true,
        min: 0,
        unit: "мм",
      },
      {
        type: "number",
        name: "shank-diameter",
        label: "Диаметр хвостовика",
        required: true,
        min: 0,
        unit: "мм",
      },
      {
        type: "textarea",
        name: "comment",
        label: "Здесь вы можете оставить комментарий к заказу",
      },
    ],
  },
};
